version: '2'
services:
  server:
    image: local/student-server
    container_name: "student-server"
    build:
      context: ./server
    links:
     - mongodb
    environment:
     - EXT_HOST_IP=192.168.1.73
    ports:
     - 3000:3000
     - 9000:9000
  mongodb:
    image: mongo:3.0.1
    container_name: "mongodb"
    environment:
     - MONGO_DATA_DIR=/data/db
     - MONGO_LOG_DIR=/dev/null
    volumes:
     - ./data/db:/data/db
    ports:
     - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null
